### ISSUE TITLE
'currentTime' and 'sampleRate' remain 0 in simulated AudioWorkletGlobalScope

### ISSUE THREAD

**Issue by JohnWeisz** [GoogleChromeLabs/audioworklet-polyfill#7]
[These lines](https://github.com/GoogleChromeLabs/audioworklet-polyfill/blob/master/src/index.js#L117) don't do anything, because the fake AudioContext properties are [copied into global scope once](https://github.com/GoogleChromeLabs/audioworklet-polyfill/blob/master/src/realm.js#L30) on initialization.

**Comment by developit** [comment]
Ah - good catch, I should have exempted them to avoid that shadowing.

**Comment by developit** [comment]
Thanks John - it looks like I'd only tested property access, which was working (`self.currentTime`, old lint habits). This issue is now fixed in [1.1.0](https://github.com/GoogleChromeLabs/audioworklet-polyfill/releases/tag/1.1.0).

**Comment by JohnWeisz** [comment]
@developit Thanks for having a go at this, but this one is still not fixed completely (neither in 1.1.0 nor 1.1.2). The problem with the current approach is that `sampleRate` is not defined until the first `process` call, so any instantiation-time use of it will yield an incorrect outcome.

This is less of a problem with `currentTime`, but it's still tied to `process` calls directly, which is incorrect. For example, a case where the main-thread AudioWorkletNode posts messages to the AudioWorkletProcessor, which is then supposed to respond without `process` being called (such as when disconnected), the outcome will be incorrect again.

Instead, the Realm must be configured correctly with getters that return directly from the working AudioContext, something like the following (which was working fine for my use-case, but I'm unsure of what side-effects it has):

**realm.js**

```diff
export function Realm (scope, parentElement) {
  const frame = document.createElement('iframe');
  frame.style.cssText = 'position:absolute;left:0;top:-999px;width:1px;height:1px;';
  parentElement.appendChild(frame);
  const win = frame.contentWindow;
  const doc = win.document;
  let vars = 'var window,$hook';
+ let accessors = "";
  for (const i in win) {
    if (!(i in scope) && i !== 'eval') {
      vars += ',';
      vars += i;
    }
  }
  for (const i in scope) {
-   vars += ',';
-   vars += i;
-   vars += '=self.';
-   vars += i;
+   accessors += `Object.defineProperty(this,'${i}',{`;
+   accessors += `    get: function(){return self.${i};},`;
+   accessors += `    set: function(v){self.${i}=v;}`;
+   accessors += `});`;
  }
  const script = doc.createElement('script');
  script.appendChild(doc.createTextNode(
    `function $hook(self,console) {"use strict";
-       ${vars};return function() {return eval(arguments[0])}}`
+       ${vars};${accessors}return function() {return eval(arguments[0])}}`
  ));
  doc.body.appendChild(script);
  this.exec = win.$hook(scope, console);
}
```

**polyfill.js**

```diff
    addModule (url, options) {
      return fetch(url).then(r => {
        if (!r.ok) throw Error(r.status);
        return r.text();
      }).then(code => {
        const context = {
          sampleRate: 0,
          currentTime: 0,
          AudioWorkletProcessor () {
            this.port = nextPort;
          },
          registerProcessor: (name, Processor) => {
            const processors = getProcessorsForContext(this.$$context);
            processors[name] = {
              realm,
              context,
              Processor,
              properties: Processor.parameterDescriptors || []
            };
          }
        };

+       Object.defineProperty(context, "sampleRate", {
+         get: () => (this as any).$$context.sampleRate
+       });
+
+       Object.defineProperty(context, "currentTime", {
+         get: () => (this as any).$$context.currentTime
+       });

        context.self = context;
        const realm = new Realm(context, document.documentElement);
        realm.exec(((options && options.transpile) || String)(code));
        return null;
      });
    }
```
